import type { Metadata } from 'next'
import { Root } from '@/components/layout/root/Root'
import { geistMono, geistSans } from '@/lib/fonts'
import '../styles/index.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-slate-50 antialiased`}
      >
        <Root>{children}</Root>
      </body>
    </html>
  )
}
